export interface FoodSeedEntry {
  name: string;
  keywords: string;
  calories: number;
  serving_size: string;
  category: string;
}

export const FOOD_SEED_DATA: FoodSeedEntry[] = [
  // ========== CARNES ==========
  { name: 'Milanesa de carne', keywords: 'milanesa,milanga,mila,milanesa de carne,milanesa de ternera,milanesas', calories: 350, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Milanesa de pollo', keywords: 'milanesa de pollo,milanga de pollo,milanesa pollo', calories: 300, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Milanesa napolitana', keywords: 'milanesa napolitana,milanga napo,napo,napolitana', calories: 520, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Bife de chorizo', keywords: 'bife de chorizo,bife,bife chorizo', calories: 400, serving_size: '200g', category: 'carnes' },
  { name: 'Bife de lomo', keywords: 'bife de lomo,lomo,lomito de carne', calories: 300, serving_size: '200g', category: 'carnes' },
  { name: 'Pollo grillado (pechuga)', keywords: 'pollo grillado,pechuga de pollo,pechuga,pollo a la plancha,pollo plancha', calories: 200, serving_size: '1 pechuga', category: 'carnes' },
  { name: 'Pollo al horno (muslo)', keywords: 'pollo al horno,muslo de pollo,pata muslo,muslo,pollo horno', calories: 280, serving_size: '1 muslo', category: 'carnes' },
  { name: 'Asado (costilla)', keywords: 'asado,costilla,asado costilla,tira de asado,costillar', calories: 450, serving_size: 'porción 200g', category: 'carnes' },
  { name: 'Vacío', keywords: 'vacio,vacío', calories: 350, serving_size: 'porción 200g', category: 'carnes' },
  { name: 'Matambre', keywords: 'matambre,matambre de cerdo,matambre arrollado', calories: 380, serving_size: 'porción 200g', category: 'carnes' },
  { name: 'Choripán', keywords: 'choripan,choripán,chori,chorizo al pan', calories: 450, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Chorizo', keywords: 'chorizo,chorizo parrillero,chorizo criollo', calories: 300, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Morcilla', keywords: 'morcilla', calories: 250, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Bondiola', keywords: 'bondiola,bondiola de cerdo', calories: 400, serving_size: 'porción 200g', category: 'carnes' },
  { name: 'Hamburguesa casera', keywords: 'hamburguesa casera,hamburguesa,burger casera', calories: 350, serving_size: '1 unidad 150g', category: 'carnes' },
  { name: 'Hamburguesa completa', keywords: 'hamburguesa completa,hamburguesa con queso,cheeseburger casera', calories: 550, serving_size: '1 unidad con pan', category: 'carnes' },
  { name: 'Albóndigas', keywords: 'albondigas,albóndigas', calories: 250, serving_size: '4 unidades', category: 'carnes' },
  { name: 'Cerdo al horno', keywords: 'cerdo al horno,cerdo,carne de cerdo,carré de cerdo', calories: 350, serving_size: 'porción 200g', category: 'carnes' },
  { name: 'Peceto', keywords: 'peceto', calories: 250, serving_size: 'porción 200g', category: 'carnes' },

  // ========== PESCADOS ==========
  { name: 'Filet de merluza', keywords: 'merluza,filet de merluza,pescado,filet de pescado', calories: 180, serving_size: '1 filet', category: 'pescados' },
  { name: 'Milanesa de merluza', keywords: 'milanesa de merluza,milanesa de pescado,milanesa pescado', calories: 280, serving_size: '1 unidad', category: 'pescados' },
  { name: 'Atún en lata', keywords: 'atun,atún,atun en lata,atún en lata,lata de atun', calories: 120, serving_size: '1 lata 170g', category: 'pescados' },
  { name: 'Salmón', keywords: 'salmon,salmón,salmón rosado', calories: 280, serving_size: 'filet 150g', category: 'pescados' },

  // ========== PASTAS ==========
  { name: 'Fideos con tuco', keywords: 'fideos con tuco,fideos con salsa,fideos tuco,fideos salsa,fideos', calories: 450, serving_size: 'plato', category: 'pastas' },
  { name: 'Fideos con pesto', keywords: 'fideos con pesto,fideos pesto', calories: 480, serving_size: 'plato', category: 'pastas' },
  { name: 'Fideos con manteca', keywords: 'fideos con manteca,fideos manteca', calories: 420, serving_size: 'plato', category: 'pastas' },
  { name: 'Ñoquis con salsa', keywords: 'ñoquis,noquis,ñoquis con salsa,ñoquis con tuco', calories: 500, serving_size: 'plato', category: 'pastas' },
  { name: 'Ravioles con salsa', keywords: 'ravioles,ravioles con salsa,ravioles de verdura,ravioles de ricota', calories: 520, serving_size: 'plato', category: 'pastas' },
  { name: 'Lasaña', keywords: 'lasaña,lasagna', calories: 550, serving_size: 'porción', category: 'pastas' },
  { name: 'Canelones', keywords: 'canelones,canelones de verdura', calories: 480, serving_size: 'porción 2 unidades', category: 'pastas' },
  { name: 'Sorrentinos', keywords: 'sorrentinos,sorrentinos con salsa', calories: 520, serving_size: 'plato', category: 'pastas' },
  { name: 'Tallarines', keywords: 'tallarines,tallarines con salsa', calories: 460, serving_size: 'plato', category: 'pastas' },
  { name: 'Fideos con bolognesa', keywords: 'fideos con bolognesa,bolognesa,boloñesa,fideos boloñesa', calories: 500, serving_size: 'plato', category: 'pastas' },

  // ========== ARROZ / LEGUMBRES ==========
  { name: 'Arroz blanco', keywords: 'arroz,arroz blanco,arroz hervido', calories: 200, serving_size: 'taza cocido', category: 'arroz' },
  { name: 'Arroz con pollo', keywords: 'arroz con pollo', calories: 450, serving_size: 'plato', category: 'arroz' },
  { name: 'Arroz primavera', keywords: 'arroz primavera,arroz con verduras', calories: 300, serving_size: 'plato', category: 'arroz' },
  { name: 'Guiso de lentejas', keywords: 'guiso de lentejas,lentejas,guiso lentejas', calories: 400, serving_size: 'plato', category: 'legumbres' },
  { name: 'Guiso de arroz', keywords: 'guiso de arroz,guiso arroz', calories: 420, serving_size: 'plato', category: 'legumbres' },
  { name: 'Locro', keywords: 'locro', calories: 500, serving_size: 'plato', category: 'legumbres' },
  { name: 'Polenta', keywords: 'polenta,polenta con salsa', calories: 350, serving_size: 'plato', category: 'legumbres' },
  { name: 'Estofado', keywords: 'estofado,estofado de carne', calories: 450, serving_size: 'plato', category: 'legumbres' },

  // ========== EMPANADAS ==========
  { name: 'Empanada de carne', keywords: 'empanada de carne,empanada carne,empanadas de carne,empanada,empanadas', calories: 280, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada de pollo', keywords: 'empanada de pollo,empanadas de pollo', calories: 260, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada de jamón y queso', keywords: 'empanada de jamon y queso,empanada jamon queso,empanada jyq', calories: 270, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada de verdura', keywords: 'empanada de verdura,empanada verdura,empanadas de verdura', calories: 220, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada de humita', keywords: 'empanada de humita,empanada humita', calories: 240, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada de carne frita', keywords: 'empanada frita,empanada de carne frita,empanadas fritas', calories: 350, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada árabe', keywords: 'empanada arabe,empanada árabe,fatay,sfija', calories: 200, serving_size: '1 unidad', category: 'empanadas' },
  { name: 'Empanada caprese', keywords: 'empanada caprese,empanada tomate queso', calories: 250, serving_size: '1 unidad', category: 'empanadas' },

  // ========== TARTAS / PIZZAS ==========
  { name: 'Pizza muzzarella (porción)', keywords: 'pizza,pizza muzzarella,pizza muzza,porcion de pizza,porción de pizza,muzza', calories: 280, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Pizza napolitana (porción)', keywords: 'pizza napolitana,pizza napo', calories: 300, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Pizza con jamón (porción)', keywords: 'pizza con jamon,pizza jamon', calories: 310, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Fugazzeta (porción)', keywords: 'fugazzeta,fugazza,fugazza con queso', calories: 320, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Fainá (porción)', keywords: 'faina,fainá', calories: 180, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Tarta de jamón y queso', keywords: 'tarta de jamon y queso,tarta jamon queso,tarta jyq,tarta', calories: 350, serving_size: 'porción', category: 'tartas' },
  { name: 'Tarta de verdura', keywords: 'tarta de verdura,tarta verdura,tarta de espinaca,pascualina', calories: 280, serving_size: 'porción', category: 'tartas' },
  { name: 'Tarta de atún', keywords: 'tarta de atun,tarta atún', calories: 320, serving_size: 'porción', category: 'tartas' },
  { name: 'Tarta de zapallitos', keywords: 'tarta de zapallitos,tarta zapallitos', calories: 290, serving_size: 'porción', category: 'tartas' },
  { name: 'Calzone', keywords: 'calzone', calories: 400, serving_size: '1 unidad', category: 'pizzas' },

  // ========== SÁNDWICHES ==========
  { name: 'Tostado de jamón y queso', keywords: 'tostado,tostado de jamon y queso,tostado jyq,tostado jamon queso,sandwich tostado', calories: 300, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Sándwich de milanesa', keywords: 'sandwich de milanesa,sanguche de milanesa,milanesa al pan,milanga al pan,sanguchito de milanga', calories: 550, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Pancho', keywords: 'pancho,hot dog,perro caliente', calories: 300, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Lomito', keywords: 'lomito,lomito completo,lomito al pan', calories: 650, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Sándwich de miga', keywords: 'sandwich de miga,sandwiches de miga,sanguche de miga', calories: 120, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Sándwich de jamón crudo y queso', keywords: 'sandwich de jamon crudo,sandwich jamon crudo queso', calories: 350, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Tostadas con jamón y queso', keywords: 'tostadas con jamon y queso', calories: 250, serving_size: '2 tostadas', category: 'sandwiches' },

  // ========== CADENAS - SUBWAY ==========
  { name: 'Subway Pollo Teriyaki 15cm', keywords: 'subway teriyaki 15cm,subway pollo teriyaki 15cm,sub teriyaki chico,subway teriyaki', calories: 470, serving_size: '1 sub 15cm', category: 'cadenas' },
  { name: 'Subway Pollo Teriyaki 30cm', keywords: 'subway teriyaki 30cm,subway pollo teriyaki 30cm,sub teriyaki footlong,sub teriyaki grande,subway teriyaki grande', calories: 940, serving_size: '1 sub 30cm', category: 'cadenas' },
  { name: 'Subway Italiano BMT 15cm', keywords: 'subway italiano 15cm,subway bmt 15cm,sub italiano', calories: 400, serving_size: '1 sub 15cm', category: 'cadenas' },
  { name: 'Subway Italiano BMT 30cm', keywords: 'subway italiano 30cm,subway bmt 30cm,sub italiano grande', calories: 800, serving_size: '1 sub 30cm', category: 'cadenas' },
  { name: 'Subway Steak & Cheese 15cm', keywords: 'subway steak cheese 15cm,subway carne queso', calories: 380, serving_size: '1 sub 15cm', category: 'cadenas' },
  { name: 'Subway Steak & Cheese 30cm', keywords: 'subway steak cheese 30cm,subway carne queso 30cm', calories: 760, serving_size: '1 sub 30cm', category: 'cadenas' },
  { name: 'Subway Veggie Delite 15cm', keywords: 'subway veggie 15cm,subway vegetariano', calories: 230, serving_size: '1 sub 15cm', category: 'cadenas' },
  { name: 'Subway Atún 15cm', keywords: 'subway atun 15cm,subway tuna 15cm', calories: 480, serving_size: '1 sub 15cm', category: 'cadenas' },
  { name: 'Subway Atún 30cm', keywords: 'subway atun 30cm,subway tuna 30cm', calories: 960, serving_size: '1 sub 30cm', category: 'cadenas' },
  { name: 'Subway Cookie', keywords: 'subway cookie,galletita subway', calories: 200, serving_size: '1 unidad', category: 'cadenas' },

  // ========== CADENAS - MCDONALD'S ==========
  { name: 'Big Mac', keywords: 'big mac,bigmac,big mac mcdonalds', calories: 550, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Cuarto de Libra con Queso', keywords: 'cuarto de libra,cuarto de libra con queso,quarter pounder', calories: 520, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'McPollo', keywords: 'mcpollo,mc pollo', calories: 400, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Triple Mac', keywords: 'triple mac,triple mc', calories: 700, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'McNuggets x6', keywords: 'mcnuggets x6,nuggets x6,nuggets 6,mc nuggets 6', calories: 270, serving_size: '6 unidades', category: 'cadenas' },
  { name: 'McNuggets x10', keywords: 'mcnuggets x10,nuggets x10,nuggets 10,mc nuggets 10', calories: 450, serving_size: '10 unidades', category: 'cadenas' },
  { name: 'Papas fritas McDonald\'s chicas', keywords: 'papas mcdonalds chicas,papas mc chicas,papas fritas chicas mc', calories: 230, serving_size: 'chicas', category: 'cadenas' },
  { name: 'Papas fritas McDonald\'s medianas', keywords: 'papas mcdonalds medianas,papas mc medianas,papas fritas medianas mc,papas medianas', calories: 340, serving_size: 'medianas', category: 'cadenas' },
  { name: 'Papas fritas McDonald\'s grandes', keywords: 'papas mcdonalds grandes,papas mc grandes,papas fritas grandes mc,papas grandes', calories: 490, serving_size: 'grandes', category: 'cadenas' },
  { name: 'McFlurry', keywords: 'mcflurry,mc flurry', calories: 340, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Sundae', keywords: 'sundae mcdonalds,sundae mc,sundae', calories: 280, serving_size: '1 unidad', category: 'cadenas' },

  // ========== CADENAS - BURGER KING ==========
  { name: 'Whopper', keywords: 'whopper,whopper burger king,whopper bk', calories: 660, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Whopper Jr', keywords: 'whopper jr,whopper junior', calories: 370, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Doble Whopper', keywords: 'doble whopper,double whopper', calories: 900, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Stacker BK', keywords: 'stacker,stacker bk,stacker burger king', calories: 580, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Papas fritas Burger King medianas', keywords: 'papas bk medianas,papas burger king medianas', calories: 380, serving_size: 'medianas', category: 'cadenas' },
  { name: 'Aros de cebolla BK', keywords: 'aros de cebolla,aros cebolla bk,onion rings', calories: 320, serving_size: 'porción', category: 'cadenas' },

  // ========== CADENAS - MOSTAZA ==========
  { name: 'Hamburguesa Mostaza Clásica', keywords: 'mostaza clasica,hamburguesa mostaza,mostaza hamburguesa', calories: 480, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Mostaza Doble', keywords: 'mostaza doble,hamburguesa doble mostaza', calories: 650, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Papas fritas Mostaza', keywords: 'papas mostaza,papas fritas mostaza', calories: 350, serving_size: 'porción', category: 'cadenas' },

  // ========== BEBIDAS ==========
  { name: 'Coca Cola', keywords: 'coca,coca cola,cocacola', calories: 140, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Coca Cola 500ml', keywords: 'coca 500,coca cola 500,coca medio litro,coca botella', calories: 210, serving_size: '500ml', category: 'bebidas' },
  { name: 'Coca Cola Zero', keywords: 'coca zero,coca cola zero,coca light,coca sin azucar', calories: 0, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Sprite', keywords: 'sprite', calories: 130, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Fanta', keywords: 'fanta,fanta naranja', calories: 140, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Agua', keywords: 'agua,agua mineral,agua con gas', calories: 0, serving_size: 'vaso', category: 'bebidas' },
  { name: 'Jugo de naranja', keywords: 'jugo de naranja,jugo naranja,jugo natural', calories: 110, serving_size: 'vaso 250ml', category: 'bebidas' },
  { name: 'Jugo en caja', keywords: 'jugo en caja,jugo baggio,jugo cepita,jugo caja', calories: 100, serving_size: 'vaso 250ml', category: 'bebidas' },
  { name: 'Cerveza', keywords: 'cerveza,birra,cerveza rubia,quilmes,brahma', calories: 150, serving_size: 'lata 355ml', category: 'bebidas' },
  { name: 'Cerveza pinta', keywords: 'cerveza pinta,pinta,pinta de cerveza', calories: 200, serving_size: 'pinta 500ml', category: 'bebidas' },
  { name: 'Vino tinto', keywords: 'vino,vino tinto,copa de vino', calories: 130, serving_size: 'copa 150ml', category: 'bebidas' },
  { name: 'Fernet con coca', keywords: 'fernet,fernet con coca,fernecito,fernet branca', calories: 250, serving_size: 'vaso', category: 'bebidas' },
  { name: 'Café solo', keywords: 'cafe,café,cafe solo,café solo,espresso,expreso', calories: 5, serving_size: '1 taza', category: 'bebidas' },
  { name: 'Café con leche', keywords: 'cafe con leche,café con leche,cortado', calories: 80, serving_size: '1 taza', category: 'bebidas' },
  { name: 'Café latte', keywords: 'cafe latte,latte,café latte', calories: 130, serving_size: '1 vaso', category: 'bebidas' },
  { name: 'Mate cocido', keywords: 'mate cocido', calories: 5, serving_size: '1 taza', category: 'bebidas' },
  { name: 'Mate (con azúcar)', keywords: 'mate dulce,mate con azucar', calories: 30, serving_size: 'por cebada', category: 'bebidas' },
  { name: 'Mate (amargo)', keywords: 'mate,mate amargo,mates', calories: 5, serving_size: 'por cebada', category: 'bebidas' },
  { name: 'Té', keywords: 'te,té', calories: 2, serving_size: '1 taza', category: 'bebidas' },
  { name: 'Gatorade', keywords: 'gatorade,bebida deportiva,bebida isotonica', calories: 130, serving_size: 'botella 500ml', category: 'bebidas' },
  { name: 'Licuado de banana', keywords: 'licuado de banana,licuado banana,licuado', calories: 200, serving_size: 'vaso', category: 'bebidas' },

  // ========== LÁCTEOS ==========
  { name: 'Yogur entero', keywords: 'yogur,yogur entero,yogurt', calories: 130, serving_size: 'pote 200g', category: 'lacteos' },
  { name: 'Yogur descremado', keywords: 'yogur descremado,yogur diet,yogur light,yogur desc', calories: 80, serving_size: 'pote 200g', category: 'lacteos' },
  { name: 'Leche entera', keywords: 'leche,leche entera,vaso de leche', calories: 120, serving_size: 'vaso 250ml', category: 'lacteos' },
  { name: 'Leche descremada', keywords: 'leche descremada,leche light,leche desc', calories: 80, serving_size: 'vaso 250ml', category: 'lacteos' },
  { name: 'Queso cremoso', keywords: 'queso cremoso,queso crema', calories: 100, serving_size: 'porción 30g', category: 'lacteos' },
  { name: 'Queso rallado', keywords: 'queso rallado', calories: 50, serving_size: 'cucharada', category: 'lacteos' },
  { name: 'Queso untable light', keywords: 'queso untable,queso light,casancrem light,finlandia light', calories: 40, serving_size: 'cucharada', category: 'lacteos' },
  { name: 'Manteca', keywords: 'manteca', calories: 100, serving_size: 'porción 15g', category: 'lacteos' },
  { name: 'Dulce de leche', keywords: 'dulce de leche,ddl', calories: 80, serving_size: 'cucharada', category: 'lacteos' },

  // ========== PAN / CEREALES ==========
  { name: 'Pan francés', keywords: 'pan,pan frances,pan francés,pan blanco', calories: 150, serving_size: '1 unidad', category: 'pan' },
  { name: 'Pan integral', keywords: 'pan integral,pan negro', calories: 130, serving_size: '2 rebanadas', category: 'pan' },
  { name: 'Pan lactal', keywords: 'pan lactal,pan de molde,pan bimbo', calories: 130, serving_size: '2 rebanadas', category: 'pan' },
  { name: 'Medialunas', keywords: 'medialuna,medialunas,medialuna de manteca,medialuna de grasa', calories: 200, serving_size: '1 unidad', category: 'pan' },
  { name: 'Tostadas', keywords: 'tostadas,tostada,tostada de pan', calories: 70, serving_size: '1 rebanada', category: 'pan' },
  { name: 'Galletitas de agua', keywords: 'galletitas de agua,galletitas,crackers', calories: 130, serving_size: '10 unidades', category: 'pan' },
  { name: 'Galletitas dulces', keywords: 'galletitas dulces,galletitas pepitos,galletitas chocolate', calories: 180, serving_size: '6 unidades', category: 'pan' },
  { name: 'Cereales', keywords: 'cereales,cereales con leche,zucaritas,copos', calories: 200, serving_size: 'taza con leche', category: 'pan' },
  { name: 'Granola', keywords: 'granola,granola con yogur', calories: 250, serving_size: '50g', category: 'pan' },
  { name: 'Avena', keywords: 'avena,avena con leche,porridge,overnight oats', calories: 180, serving_size: '40g cocida', category: 'pan' },
  { name: 'Tortilla de trigo', keywords: 'tortilla de trigo,tortilla,wrap', calories: 150, serving_size: '1 unidad', category: 'pan' },

  // ========== FRUTAS ==========
  { name: 'Manzana', keywords: 'manzana', calories: 80, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Banana', keywords: 'banana,bananas', calories: 100, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Naranja', keywords: 'naranja', calories: 60, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Mandarina', keywords: 'mandarina', calories: 40, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Uvas', keywords: 'uvas,uva', calories: 70, serving_size: 'racimo chico', category: 'frutas' },
  { name: 'Durazno', keywords: 'durazno', calories: 60, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Pera', keywords: 'pera', calories: 80, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Sandía', keywords: 'sandia,sandía', calories: 50, serving_size: 'tajada', category: 'frutas' },
  { name: 'Melón', keywords: 'melon,melón', calories: 50, serving_size: 'tajada', category: 'frutas' },
  { name: 'Frutilla', keywords: 'frutillas,frutilla', calories: 40, serving_size: 'taza', category: 'frutas' },
  { name: 'Kiwi', keywords: 'kiwi', calories: 50, serving_size: '1 unidad', category: 'frutas' },
  { name: 'Ananá', keywords: 'anana,ananá,piña', calories: 80, serving_size: 'rodaja', category: 'frutas' },
  { name: 'Palta', keywords: 'palta,aguacate', calories: 160, serving_size: '1/2 unidad', category: 'frutas' },
  { name: 'Cereza', keywords: 'cerezas,cereza', calories: 50, serving_size: 'taza', category: 'frutas' },
  { name: 'Frutos secos mix', keywords: 'frutos secos,mix frutos secos,nueces,almendras,mani,maní', calories: 180, serving_size: 'puñado 30g', category: 'frutas' },

  // ========== VERDURAS / GUARNICIONES ==========
  { name: 'Ensalada simple', keywords: 'ensalada,ensalada simple,ensalada verde,ensalada de lechuga', calories: 50, serving_size: 'plato', category: 'verduras' },
  { name: 'Ensalada mixta', keywords: 'ensalada mixta,ensalada completa,ensalada con tomate', calories: 100, serving_size: 'plato', category: 'verduras' },
  { name: 'Ensalada César', keywords: 'ensalada cesar,ensalada césar,cesar,caesar', calories: 300, serving_size: 'plato', category: 'verduras' },
  { name: 'Tomate', keywords: 'tomate', calories: 25, serving_size: '1 unidad', category: 'verduras' },
  { name: 'Lechuga', keywords: 'lechuga', calories: 10, serving_size: 'porción', category: 'verduras' },
  { name: 'Zanahoria', keywords: 'zanahoria', calories: 35, serving_size: '1 unidad', category: 'verduras' },
  { name: 'Papa hervida', keywords: 'papa hervida,papa,papas hervidas', calories: 130, serving_size: '1 unidad mediana', category: 'verduras' },
  { name: 'Puré de papas', keywords: 'pure,puré,pure de papas,puré de papas,pure de papa', calories: 200, serving_size: 'porción', category: 'verduras' },
  { name: 'Puré de calabaza', keywords: 'pure de calabaza,puré de calabaza,pure calabaza', calories: 120, serving_size: 'porción', category: 'verduras' },
  { name: 'Batata hervida', keywords: 'batata,batata hervida,boniato', calories: 120, serving_size: '1 unidad', category: 'verduras' },
  { name: 'Zapallo hervido', keywords: 'zapallo,zapallo hervido,calabaza', calories: 50, serving_size: 'porción', category: 'verduras' },
  { name: 'Choclo hervido', keywords: 'choclo,choclo hervido,maiz,mazorca', calories: 130, serving_size: '1 unidad', category: 'verduras' },
  { name: 'Papas fritas caseras', keywords: 'papas fritas,papas fritas caseras', calories: 350, serving_size: 'porción', category: 'verduras' },
  { name: 'Revuelto de verduras', keywords: 'revuelto de verduras,verduras salteadas,wok de verduras', calories: 150, serving_size: 'porción', category: 'verduras' },
  { name: 'Zapallitos rellenos', keywords: 'zapallitos rellenos,zapallito relleno', calories: 250, serving_size: '2 unidades', category: 'verduras' },

  // ========== HUEVOS ==========
  { name: 'Huevo frito', keywords: 'huevo frito,huevos fritos', calories: 120, serving_size: '1 unidad', category: 'huevos' },
  { name: 'Huevo revuelto', keywords: 'huevo revuelto,huevos revueltos,scrambled', calories: 100, serving_size: '1 unidad', category: 'huevos' },
  { name: 'Huevo duro', keywords: 'huevo duro,huevos duros,huevo hervido', calories: 75, serving_size: '1 unidad', category: 'huevos' },
  { name: 'Omelette', keywords: 'omelette,tortilla de huevo,omelette de queso', calories: 250, serving_size: '2 huevos', category: 'huevos' },
  { name: 'Tortilla de papas', keywords: 'tortilla de papas,tortilla española,tortilla papa', calories: 300, serving_size: 'porción', category: 'huevos' },

  // ========== SNACKS / DULCES ==========
  { name: 'Alfajor simple', keywords: 'alfajor,alfajor simple,alfajor maicena,alfajor de maicena', calories: 200, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Alfajor triple', keywords: 'alfajor triple,alfajor havanna,alfajor cachafaz,triple', calories: 400, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Alfajor de arroz', keywords: 'alfajor de arroz,alfajor arroz', calories: 100, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Barra de cereal', keywords: 'barra de cereal,barrita de cereal,barrita', calories: 120, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Chocolate', keywords: 'chocolate,barra de chocolate,tableta de chocolate', calories: 250, serving_size: 'barra 50g', category: 'snacks' },
  { name: 'Galletitas Oreo', keywords: 'oreo,galletitas oreo,oreos', calories: 160, serving_size: '4 unidades', category: 'snacks' },
  { name: 'Papas fritas de paquete', keywords: 'papas de paquete,lays,papas snack,papitas', calories: 280, serving_size: 'paquete chico 75g', category: 'snacks' },
  { name: 'Palitos salados', keywords: 'palitos,palitos salados', calories: 150, serving_size: 'paquete chico', category: 'snacks' },
  { name: 'Maní con chocolate', keywords: 'mani con chocolate,maní con chocolate,rocklets', calories: 250, serving_size: 'paquete 50g', category: 'snacks' },
  { name: 'Helado 1 bocha', keywords: 'helado,helado 1 bocha,bocha de helado,helado bocha', calories: 150, serving_size: '1 bocha', category: 'snacks' },
  { name: 'Helado 1/4 kg', keywords: 'helado cuarto,helado 1/4,helado 250g,cuarto de helado,cuarto kilo helado', calories: 400, serving_size: '1/4 kg', category: 'snacks' },
  { name: 'Helado 1/2 kg', keywords: 'helado medio,helado 1/2,helado 500g,medio kilo helado', calories: 800, serving_size: '1/2 kg', category: 'snacks' },

  // ========== POSTRES ==========
  { name: 'Flan', keywords: 'flan,flan casero', calories: 200, serving_size: '1 porción', category: 'postres' },
  { name: 'Flan con dulce de leche', keywords: 'flan con dulce de leche,flan con ddl,flan ddl', calories: 300, serving_size: '1 porción', category: 'postres' },
  { name: 'Flan con crema', keywords: 'flan con crema', calories: 320, serving_size: '1 porción', category: 'postres' },
  { name: 'Ensalada de frutas', keywords: 'ensalada de frutas,ensalada de fruta,macedonea', calories: 150, serving_size: '1 bowl', category: 'postres' },
  { name: 'Tiramisú', keywords: 'tiramisu,tiramisú', calories: 350, serving_size: '1 porción', category: 'postres' },
  { name: 'Torta (porción)', keywords: 'torta,porcion de torta,torta chocolate,torta cumple', calories: 350, serving_size: '1 porción', category: 'postres' },
  { name: 'Budín', keywords: 'budin,budín,budin de pan,budín de pan', calories: 300, serving_size: '1 porción', category: 'postres' },
  { name: 'Panqueques con dulce de leche', keywords: 'panqueques,panqueque,panqueques con dulce de leche,panqueques ddl', calories: 350, serving_size: '2 unidades', category: 'postres' },
  { name: 'Churros', keywords: 'churros,churro', calories: 250, serving_size: '3 unidades', category: 'postres' },
  { name: 'Facturas (criollito)', keywords: 'factura,facturas,criollito,sacramento,medialuna rellena', calories: 250, serving_size: '1 unidad', category: 'postres' },
  { name: 'Brownie', keywords: 'brownie', calories: 300, serving_size: '1 porción', category: 'postres' },
  { name: 'Cheesecake (porción)', keywords: 'cheesecake,cheese cake,tarta de queso', calories: 350, serving_size: '1 porción', category: 'postres' },

  // ========== SALSAS / EXTRAS ==========
  { name: 'Mayonesa', keywords: 'mayonesa,mayo', calories: 100, serving_size: 'cucharada', category: 'extras' },
  { name: 'Ketchup', keywords: 'ketchup,catchup', calories: 20, serving_size: 'cucharada', category: 'extras' },
  { name: 'Mostaza (salsa)', keywords: 'mostaza salsa,salsa mostaza', calories: 10, serving_size: 'cucharada', category: 'extras' },
  { name: 'Salsa golf', keywords: 'salsa golf,golf', calories: 80, serving_size: 'cucharada', category: 'extras' },
  { name: 'Aceite de oliva', keywords: 'aceite,aceite de oliva,aceite oliva', calories: 120, serving_size: 'cucharada', category: 'extras' },
  { name: 'Mermelada', keywords: 'mermelada', calories: 50, serving_size: 'cucharada', category: 'extras' },
  { name: 'Miel', keywords: 'miel', calories: 60, serving_size: 'cucharada', category: 'extras' },
  { name: 'Queso rallado', keywords: 'queso rallado,parmesano', calories: 50, serving_size: 'cucharada', category: 'extras' },
  { name: 'Azúcar', keywords: 'azucar,azúcar,cucharada de azucar', calories: 40, serving_size: 'cucharada', category: 'extras' },

  // ========== COMIDAS PREPARADAS ==========
  { name: 'Sushi roll (8 piezas)', keywords: 'sushi,sushi roll,roll de sushi,maki', calories: 350, serving_size: '8 piezas', category: 'preparadas' },
  { name: 'Sushi salmón (pieza)', keywords: 'nigiri,nigiri salmon,pieza sushi', calories: 50, serving_size: '1 pieza', category: 'preparadas' },
  { name: 'Wrap de pollo', keywords: 'wrap,wrap de pollo,wrap pollo', calories: 400, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Ensalada de arroz', keywords: 'ensalada de arroz,arroz con mayonesa', calories: 350, serving_size: 'plato', category: 'preparadas' },
  { name: 'Milanesa al pan', keywords: 'milanesa al pan,sandwich milanesa,sanguche milanesa', calories: 550, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Suprema', keywords: 'suprema,suprema de pollo,suprema maryland', calories: 320, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Pebete de jamón y queso', keywords: 'pebete,pebete jamon queso', calories: 280, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Tacos', keywords: 'tacos,taco', calories: 200, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Burrito', keywords: 'burrito', calories: 500, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Wok de pollo', keywords: 'wok de pollo,wok pollo,pollo wok', calories: 400, serving_size: 'plato', category: 'preparadas' },
  { name: 'Wok de carne', keywords: 'wok de carne,wok carne', calories: 450, serving_size: 'plato', category: 'preparadas' },
  { name: 'Crepe salado', keywords: 'crepe,crepe salado,crepe de jamon y queso', calories: 300, serving_size: '1 unidad', category: 'preparadas' },
  { name: 'Taco de carne', keywords: 'taco de carne,taco carne', calories: 220, serving_size: '1 unidad', category: 'preparadas' },

  // ========== CADENAS - GRIDO ==========
  { name: 'Grido helado 1/4 kg', keywords: 'grido cuarto,grido 1/4,helado grido cuarto,grido 250', calories: 380, serving_size: '1/4 kg', category: 'cadenas' },
  { name: 'Grido helado 1/2 kg', keywords: 'grido medio,grido 1/2,helado grido medio,grido 500', calories: 760, serving_size: '1/2 kg', category: 'cadenas' },
  { name: 'Grido helado 1 kg', keywords: 'grido kilo,grido 1kg,helado grido kilo', calories: 1520, serving_size: '1 kg', category: 'cadenas' },
  { name: 'Grido cucurucho', keywords: 'grido cucurucho,cucurucho grido,cono grido', calories: 220, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Grido palito helado', keywords: 'grido palito,palito grido,palito helado grido', calories: 180, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Grido vasito', keywords: 'grido vasito,vasito grido,grido vaso', calories: 150, serving_size: '1 unidad', category: 'cadenas' },

  // ========== CADENAS - HAVANNA ==========
  { name: 'Alfajor Havanna chocolate', keywords: 'havanna chocolate,alfajor havanna chocolate,havanna choco', calories: 280, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Alfajor Havanna blanco', keywords: 'havanna blanco,alfajor havanna blanco,havanna merengue', calories: 260, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Alfajor Havanna 70% cacao', keywords: 'havanna 70,havanna cacao,alfajor havanna 70 cacao', calories: 270, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Havanna café con leche', keywords: 'havanna cafe con leche,cafe havanna,havanna cortado', calories: 90, serving_size: '1 taza', category: 'cadenas' },
  { name: 'Havanna submarino', keywords: 'havanna submarino,submarino havanna,chocolate caliente havanna', calories: 280, serving_size: '1 taza', category: 'cadenas' },
  { name: 'Havanna medialuna con jamón y queso', keywords: 'havanna medialuna,medialuna havanna jyq', calories: 320, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Havanna tostado', keywords: 'havanna tostado,tostado havanna', calories: 340, serving_size: '1 unidad', category: 'cadenas' },

  // ========== CADENAS - STARBUCKS ==========
  { name: 'Starbucks Latte Grande', keywords: 'starbucks latte,latte starbucks,starbucks latte grande', calories: 190, serving_size: 'grande 473ml', category: 'cadenas' },
  { name: 'Starbucks Cappuccino Grande', keywords: 'starbucks cappuccino,cappuccino starbucks', calories: 120, serving_size: 'grande 473ml', category: 'cadenas' },
  { name: 'Starbucks Frappuccino Mocha', keywords: 'starbucks frappuccino,frappuccino,frapuccino,frappe starbucks,starbucks mocha', calories: 370, serving_size: 'grande 473ml', category: 'cadenas' },
  { name: 'Starbucks Frappuccino Caramelo', keywords: 'starbucks caramelo,frappuccino caramelo,frappe caramelo', calories: 380, serving_size: 'grande 473ml', category: 'cadenas' },
  { name: 'Starbucks Flat White', keywords: 'starbucks flat white,flat white', calories: 170, serving_size: 'grande 473ml', category: 'cadenas' },
  { name: 'Starbucks Muffin', keywords: 'starbucks muffin,muffin starbucks', calories: 340, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Starbucks Croissant', keywords: 'starbucks croissant,croissant starbucks', calories: 280, serving_size: '1 unidad', category: 'cadenas' },

  // ========== CADENAS - KFC ==========
  { name: 'KFC pieza de pollo original', keywords: 'kfc pieza,kfc pollo,pieza kfc,pollo kfc,kentucky', calories: 320, serving_size: '1 pieza', category: 'cadenas' },
  { name: 'KFC Crispy Strips x3', keywords: 'kfc crispy,kfc strips,kfc tiras,crispy strips kfc', calories: 350, serving_size: '3 unidades', category: 'cadenas' },
  { name: 'KFC Bucket 6 piezas', keywords: 'kfc bucket,bucket kfc,balde kfc,kfc 6 piezas', calories: 1920, serving_size: '6 piezas', category: 'cadenas' },
  { name: 'KFC Sándwich Crispy', keywords: 'kfc sandwich,sandwich kfc,kfc crispy sandwich', calories: 480, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'KFC Papas medianas', keywords: 'kfc papas,papas kfc,papas fritas kfc', calories: 320, serving_size: 'medianas', category: 'cadenas' },
  { name: 'KFC Coleslaw', keywords: 'kfc coleslaw,coleslaw kfc,ensalada kfc', calories: 170, serving_size: 'porción', category: 'cadenas' },

  // ========== CADENAS - WENDY'S ==========
  { name: 'Wendy\'s Classic Single', keywords: 'wendys classic,wendys hamburguesa,wendy single,wendys single', calories: 570, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Wendy\'s Dave\'s Double', keywords: 'wendys doble,wendys dave double,wendys double', calories: 810, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Wendy\'s Jr Bacon Cheeseburger', keywords: 'wendys jr bacon,wendys junior,wendys bacon', calories: 380, serving_size: '1 unidad', category: 'cadenas' },
  { name: 'Wendy\'s Papas medianas', keywords: 'wendys papas,papas wendys', calories: 350, serving_size: 'medianas', category: 'cadenas' },
  { name: 'Wendy\'s Frosty', keywords: 'wendys frosty,frosty wendys,frosty', calories: 340, serving_size: 'mediano', category: 'cadenas' },

  // ========== CADENAS - PIZZA HUT ==========
  { name: 'Pizza Hut Muzzarella (porción)', keywords: 'pizza hut muzza,pizza hut muzzarella,porcion pizza hut', calories: 300, serving_size: '1 porción', category: 'cadenas' },
  { name: 'Pizza Hut Pepperoni (porción)', keywords: 'pizza hut pepperoni,pepperoni pizza hut', calories: 330, serving_size: '1 porción', category: 'cadenas' },
  { name: 'Pizza Hut Supreme (porción)', keywords: 'pizza hut supreme,pizza hut especial', calories: 350, serving_size: '1 porción', category: 'cadenas' },
  { name: 'Pizza Hut Breadsticks', keywords: 'pizza hut breadsticks,palitos pizza hut,grisines pizza hut', calories: 200, serving_size: '2 unidades', category: 'cadenas' },

  // ========== PRODUCTOS SUPERMERCADO - YOGURES ==========
  { name: 'Yogur Ser firme', keywords: 'yogur ser,ser firme,yogur ser firme,ser descremado', calories: 70, serving_size: 'pote 190g', category: 'lacteos' },
  { name: 'Yogur Ser bebible', keywords: 'yogur ser bebible,ser bebible,ser botella', calories: 90, serving_size: 'botella 185g', category: 'lacteos' },
  { name: 'Yogurísimo entero', keywords: 'yogurisimo,yogurísimo,yogurisimo entero', calories: 140, serving_size: 'pote 190g', category: 'lacteos' },
  { name: 'Yogurísimo bebible', keywords: 'yogurisimo bebible,yogurísimo bebible', calories: 150, serving_size: 'botella 200g', category: 'lacteos' },
  { name: 'Danette chocolate', keywords: 'danette,danette chocolate,postre danette,danette choco', calories: 160, serving_size: 'pote 95g', category: 'lacteos' },
  { name: 'Danette dulce de leche', keywords: 'danette dulce de leche,danette ddl', calories: 155, serving_size: 'pote 95g', category: 'lacteos' },
  { name: 'Danette vainilla', keywords: 'danette vainilla', calories: 150, serving_size: 'pote 95g', category: 'lacteos' },
  { name: 'Danonino', keywords: 'danonino,dino,danonino frutilla', calories: 65, serving_size: 'pote 80g', category: 'lacteos' },
  { name: 'Postrecito Ser', keywords: 'postrecito ser,postre ser,ser postre', calories: 80, serving_size: 'pote 100g', category: 'lacteos' },
  { name: 'Mousse de chocolate', keywords: 'mousse,mousse chocolate,mousse de chocolate', calories: 200, serving_size: 'pote 100g', category: 'lacteos' },
  { name: 'Queso Port Salut', keywords: 'port salut,queso port salut,port salud', calories: 110, serving_size: 'porción 30g', category: 'lacteos' },
  { name: 'Queso de máquina', keywords: 'queso de maquina,queso maquina,queso de máquina,queso de fiambrería,queso barra', calories: 100, serving_size: 'porción 30g', category: 'lacteos' },
  { name: 'Leche chocolatada La Serenísima', keywords: 'leche chocolatada,leche chocolatada serenisima,la serenisima chocolatada,chocolatada', calories: 180, serving_size: 'vaso 250ml', category: 'lacteos' },

  // ========== PRODUCTOS SUPERMERCADO - BARRITAS ==========
  { name: 'Nature Valley granola bar', keywords: 'nature valley,barrita nature valley,nature valley granola', calories: 190, serving_size: '1 paquete 2 barras', category: 'snacks' },
  { name: 'Barrita Quaker', keywords: 'barrita quaker,quaker barra,barra quaker', calories: 110, serving_size: '1 unidad', category: 'snacks' },

  // ========== PRODUCTOS SUPERMERCADO - GALLETITAS ==========
  { name: 'Galletitas Toddy', keywords: 'toddy,galletitas toddy,toddy chocolate', calories: 200, serving_size: '6 unidades', category: 'snacks' },
  { name: 'Galletitas Rumba', keywords: 'rumba,galletitas rumba', calories: 170, serving_size: '4 unidades', category: 'snacks' },
  { name: 'Galletitas Lincoln', keywords: 'lincoln,galletitas lincoln', calories: 160, serving_size: '6 unidades', category: 'snacks' },
  { name: 'Tostadas Melba', keywords: 'melba,tostadas melba,galletitas melba', calories: 100, serving_size: '6 unidades', category: 'snacks' },
  { name: 'Galletitas Criollitas', keywords: 'criollitas,galletitas criollitas', calories: 130, serving_size: '8 unidades', category: 'snacks' },
  { name: 'Galletitas Rex', keywords: 'rex,galletitas rex', calories: 150, serving_size: '6 unidades', category: 'snacks' },
  { name: 'Galletitas Pepitos', keywords: 'pepitos,galletitas pepitos,pepitos chocolate', calories: 190, serving_size: '6 unidades', category: 'snacks' },
  { name: 'Galletitas Terrabusi variedad', keywords: 'terrabusi,galletitas terrabusi,variedad terrabusi', calories: 170, serving_size: '6 unidades', category: 'snacks' },
  { name: 'Galletitas Ópera', keywords: 'opera,ópera,galletitas opera', calories: 160, serving_size: '4 unidades', category: 'snacks' },

  // ========== PRODUCTOS SUPERMERCADO - CEREALES ==========
  { name: 'Cereales Granix', keywords: 'granix,cereales granix,granola granix', calories: 180, serving_size: 'taza 40g', category: 'pan' },
  { name: 'Zucaritas', keywords: 'zucaritas,cereales zucaritas,frosted flakes', calories: 190, serving_size: 'taza 40g con leche', category: 'pan' },
  { name: 'Cereales Nesquik', keywords: 'cereales nesquik,nesquik cereales', calories: 200, serving_size: 'taza 40g con leche', category: 'pan' },

  // ========== SNACKS ARGENTINOS ==========
  { name: 'Lays clásicas', keywords: 'lays,lays clasicas,papas lays', calories: 270, serving_size: 'paquete 75g', category: 'snacks' },
  { name: 'Lays stax', keywords: 'lays stax,stax', calories: 250, serving_size: 'paquete 75g', category: 'snacks' },
  { name: 'Pringles', keywords: 'pringles', calories: 530, serving_size: 'tubo 124g', category: 'snacks' },
  { name: 'Pringles (porción)', keywords: 'pringles porcion,pringles poco', calories: 150, serving_size: '15 unidades', category: 'snacks' },
  { name: 'Doritos', keywords: 'doritos,doritos queso', calories: 260, serving_size: 'paquete 75g', category: 'snacks' },
  { name: 'Chizitos', keywords: 'chizitos,cheetos', calories: 240, serving_size: 'paquete 65g', category: 'snacks' },
  { name: 'Conitos', keywords: 'conitos,3d conitos', calories: 250, serving_size: 'paquete 65g', category: 'snacks' },
  { name: 'Tutucas', keywords: 'tutucas,tutuca', calories: 220, serving_size: 'paquete 65g', category: 'snacks' },
  { name: 'Palitos de queso', keywords: 'palitos de queso,palitos queso', calories: 180, serving_size: 'paquete chico', category: 'snacks' },
  { name: 'Bon o Bon', keywords: 'bon o bon,bonobon', calories: 75, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Rhodesia', keywords: 'rhodesia,oblea rhodesia', calories: 90, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Shot', keywords: 'shot,shot chocolate,shot felfort', calories: 80, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Cabsha', keywords: 'cabsha,bocadito cabsha', calories: 70, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Capitán del Espacio', keywords: 'capitan del espacio,capitán del espacio,alfajor capitan del espacio', calories: 290, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Guaymallén triple', keywords: 'guaymallon,guaymallén,alfajor guaymallon,guaymallon triple', calories: 300, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Jorgito', keywords: 'jorgito,alfajor jorgito,jorgito negro', calories: 250, serving_size: '1 unidad', category: 'snacks' },
  { name: 'Aguila chocolate', keywords: 'aguila,chocolate aguila,aguila chocolate', calories: 270, serving_size: 'barra 50g', category: 'snacks' },
  { name: 'Milka chocolate', keywords: 'milka,chocolate milka,milka oreo', calories: 260, serving_size: 'barra 50g', category: 'snacks' },
  { name: 'Cofler chocolate', keywords: 'cofler,chocolate cofler', calories: 265, serving_size: 'barra 50g', category: 'snacks' },
  { name: 'Mantecol', keywords: 'mantecol,mantecol nucrem', calories: 220, serving_size: 'porción 40g', category: 'snacks' },

  // ========== BEBIDAS ARGENTINAS ==========
  { name: 'Manaos Cola', keywords: 'manaos,manaos cola,coca manaos', calories: 140, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Manaos Cola 2.25L', keywords: 'manaos grande,manaos 2 litros,manaos 2.25', calories: 900, serving_size: 'botella 2.25L', category: 'bebidas' },
  { name: 'Cunnington Cola', keywords: 'cunnington,cunnington cola', calories: 135, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Terma', keywords: 'terma,terma limon,terma pomelo,amargo terma', calories: 45, serving_size: 'vaso 250ml', category: 'bebidas' },
  { name: 'Paso de los Toros', keywords: 'paso de los toros,pdlt,pomelo paso de los toros,tonica', calories: 120, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Paso de los Toros Light', keywords: 'paso de los toros light,pdlt light,paso light', calories: 5, serving_size: 'vaso 350ml', category: 'bebidas' },
  { name: 'Speed energizante', keywords: 'speed,speed energizante,speed energy', calories: 115, serving_size: 'lata 250ml', category: 'bebidas' },
  { name: 'Monster Energy', keywords: 'monster,monster energy,monster energizante', calories: 110, serving_size: 'lata 473ml', category: 'bebidas' },
  { name: 'Red Bull', keywords: 'red bull,redbull', calories: 110, serving_size: 'lata 250ml', category: 'bebidas' },
  { name: 'Powerade', keywords: 'powerade,powerade isotonica', calories: 120, serving_size: 'botella 500ml', category: 'bebidas' },
  { name: 'Levité', keywords: 'levite,levité,agua saborizada levite', calories: 80, serving_size: 'botella 500ml', category: 'bebidas' },
  { name: 'Baggio en caja 1L', keywords: 'baggio caja,jugo baggio 1 litro,baggio litro', calories: 400, serving_size: '1 litro', category: 'bebidas' },
  { name: 'Ades de soja', keywords: 'ades,ades soja,jugo ades,leche de soja ades', calories: 100, serving_size: 'vaso 250ml', category: 'bebidas' },
  { name: 'Ades de almendras', keywords: 'ades almendras,leche almendras ades', calories: 50, serving_size: 'vaso 250ml', category: 'bebidas' },
  { name: 'Campari con naranja', keywords: 'campari,campari naranja,campari con jugo', calories: 180, serving_size: 'vaso', category: 'bebidas' },
  { name: 'Gancia', keywords: 'gancia,gancia con sprite,gancia tonica', calories: 170, serving_size: 'vaso', category: 'bebidas' },
  { name: 'Aperol Spritz', keywords: 'aperol,aperol spritz,spritz', calories: 200, serving_size: 'copa', category: 'bebidas' },

  // ========== COMIDA TÍPICA ARGENTINA ==========
  { name: 'Matambre a la pizza', keywords: 'matambre a la pizza,matambre pizza,matambre tirado a la pizza', calories: 480, serving_size: 'porción', category: 'carnes' },
  { name: 'Milanesa a caballo', keywords: 'milanesa a caballo,milanga a caballo,milanesa con huevo', calories: 470, serving_size: '1 unidad', category: 'carnes' },
  { name: 'Revuelto Gramajo', keywords: 'revuelto gramajo,gramajo', calories: 420, serving_size: 'porción', category: 'preparadas' },
  { name: 'Vitel toné', keywords: 'vitel tone,vitel toné,vittel tone,viteloné', calories: 380, serving_size: 'porción', category: 'carnes' },
  { name: 'Lengua a la vinagreta', keywords: 'lengua a la vinagreta,lengua vinagreta,lengua', calories: 320, serving_size: 'porción', category: 'carnes' },
  { name: 'Carbonada', keywords: 'carbonada,carbonada criolla', calories: 400, serving_size: 'plato', category: 'legumbres' },
  { name: 'Cazuela de pollo', keywords: 'cazuela,cazuela de pollo,cazuela de gallina', calories: 350, serving_size: 'plato', category: 'legumbres' },
  { name: 'Empanada gallega', keywords: 'empanada gallega,tarta gallega', calories: 380, serving_size: 'porción', category: 'empanadas' },
  { name: 'Puchero', keywords: 'puchero,puchero criollo', calories: 380, serving_size: 'plato', category: 'legumbres' },
  { name: 'Mondongo', keywords: 'mondongo,mondongo a la española,buseca', calories: 350, serving_size: 'plato', category: 'legumbres' },
  { name: 'Provoleta', keywords: 'provoleta,provolone a la parrilla,provolone', calories: 280, serving_size: 'porción', category: 'carnes' },
  { name: 'Morcipán', keywords: 'morcipan,morcipán,morcilla al pan', calories: 400, serving_size: '1 unidad', category: 'sandwiches' },
  { name: 'Entraña', keywords: 'entraña,entraña a la parrilla', calories: 380, serving_size: 'porción 200g', category: 'carnes' },
  { name: 'Chinchulín', keywords: 'chinchulin,chinchulín,chinchulín de vaca', calories: 300, serving_size: 'porción', category: 'carnes' },
  { name: 'Molleja', keywords: 'molleja,mollejas a la parrilla,mollejas', calories: 250, serving_size: 'porción', category: 'carnes' },
  { name: 'Riñón', keywords: 'riñon,riñón,riñones a la parrilla', calories: 200, serving_size: 'porción', category: 'carnes' },

  // ========== DESAYUNO / MERIENDA ==========
  { name: 'Tostadas con mermelada', keywords: 'tostadas con mermelada,tostada con mermelada', calories: 160, serving_size: '2 tostadas', category: 'pan' },
  { name: 'Tostadas con queso y dulce', keywords: 'tostadas con queso,tostadas con dulce de leche,tostadas con manteca', calories: 200, serving_size: '2 tostadas', category: 'pan' },
  { name: 'Medialuna con jamón y queso', keywords: 'medialuna jamon queso,medialuna jyq,medialuna rellena jyq', calories: 310, serving_size: '1 unidad', category: 'pan' },
  { name: 'Criollitos', keywords: 'criollitos,criollito de grasa,pancito criollito', calories: 180, serving_size: '1 unidad', category: 'pan' },
  { name: 'Vigilante (queso y dulce)', keywords: 'vigilante,queso con dulce de membrillo,queso y dulce,queso con dulce de batata,postre vigilante', calories: 250, serving_size: 'porción', category: 'postres' },
  { name: 'Bizcochitos de grasa', keywords: 'bizcochitos,bizcochitos de grasa,bizcochos de grasa', calories: 80, serving_size: '1 unidad', category: 'pan' },
  { name: 'Dulce de membrillo', keywords: 'dulce de membrillo,membrillo', calories: 70, serving_size: 'porción 30g', category: 'extras' },
  { name: 'Dulce de batata', keywords: 'dulce de batata,batata dulce', calories: 75, serving_size: 'porción 30g', category: 'extras' },
  { name: 'Submarino', keywords: 'submarino,chocolate submarino,leche con chocolate', calories: 250, serving_size: '1 taza', category: 'bebidas' },
  { name: 'Tostada con palta', keywords: 'tostada con palta,tostada palta,pan con palta', calories: 220, serving_size: '1 tostada', category: 'pan' },

  // ========== PANIFICADOS ==========
  { name: 'Prepizza', keywords: 'prepizza,pre pizza,pizza casera prepizza', calories: 600, serving_size: '1 unidad (individual)', category: 'pizzas' },
  { name: 'Fugazzeta rellena (porción)', keywords: 'fugazzeta rellena,fugazza rellena,fugazzeta rellena porcion', calories: 400, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Pizza al molde (porción)', keywords: 'pizza de cancha,pizza al molde,pizza molde,pizza media masa', calories: 320, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Pizza a la piedra (porción)', keywords: 'pizza a la piedra,pizza piedra,pizza fina', calories: 250, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Calzón de roquefort', keywords: 'calzon roquefort,calzón roquefort,calzone roquefort,calzone roquefort jamon', calories: 450, serving_size: '1 unidad', category: 'pizzas' },
  { name: 'Pizza con palmitos (porción)', keywords: 'pizza palmitos,pizza con palmitos', calories: 290, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Pizza con huevo (porción)', keywords: 'pizza con huevo,pizza huevo frito', calories: 340, serving_size: '1 porción', category: 'pizzas' },
  { name: 'Pizza cuatro quesos (porción)', keywords: 'pizza cuatro quesos,pizza 4 quesos', calories: 360, serving_size: '1 porción', category: 'pizzas' },

  // ========== MÁS COMIDAS PREPARADAS ==========
  { name: 'Fideos con crema', keywords: 'fideos con crema,fideos crema,pasta con crema', calories: 500, serving_size: 'plato', category: 'pastas' },
  { name: 'Ñoquis de papa', keywords: 'ñoquis de papa,ñoquis caseros,ñoqui de papa', calories: 480, serving_size: 'plato', category: 'pastas' },
  { name: 'Croquetas de papa', keywords: 'croquetas,croquetas de papa,croqueta', calories: 200, serving_size: '4 unidades', category: 'preparadas' },
  { name: 'Tarta de choclo', keywords: 'tarta de choclo,tarta choclo', calories: 300, serving_size: 'porción', category: 'tartas' },
  { name: 'Tarta caprese', keywords: 'tarta caprese,tarta tomate mozzarella', calories: 310, serving_size: 'porción', category: 'tartas' },
  { name: 'Suprema a la Maryland', keywords: 'maryland,suprema maryland,pollo maryland', calories: 550, serving_size: '1 plato', category: 'preparadas' },
  { name: 'Arroz con leche', keywords: 'arroz con leche', calories: 200, serving_size: 'porción', category: 'postres' },
  { name: 'Pastel de papa', keywords: 'pastel de papa,pastel de papas,pastel de carne', calories: 400, serving_size: 'porción', category: 'preparadas' },
  { name: 'Tarta de pollo', keywords: 'tarta de pollo,tarta pollo', calories: 330, serving_size: 'porción', category: 'tartas' },
  { name: 'Carne al horno con papas', keywords: 'carne al horno,carne con papas,carne horno', calories: 480, serving_size: 'plato', category: 'carnes' },
  { name: 'Pollo al disco', keywords: 'pollo al disco,disco de pollo', calories: 420, serving_size: 'plato', category: 'carnes' },
  { name: 'Humita en chala', keywords: 'humita,humita en chala,humita en olla', calories: 200, serving_size: '1 unidad', category: 'legumbres' },
  { name: 'Tamales', keywords: 'tamales,tamal', calories: 250, serving_size: '1 unidad', category: 'legumbres' },

  // ========== EXTRAS ==========
  { name: 'Chimichurri', keywords: 'chimichurri,chimi', calories: 30, serving_size: 'cucharada', category: 'extras' },
  { name: 'Criolla (salsa)', keywords: 'criolla,salsa criolla', calories: 15, serving_size: 'cucharada', category: 'extras' },
  { name: 'Salsa blanca', keywords: 'salsa blanca,bechamel,bechamel casera', calories: 50, serving_size: 'cucharada', category: 'extras' },
  { name: 'Queso untable entero', keywords: 'queso untable,casancrem,finlandia,queso philadelphia', calories: 60, serving_size: 'cucharada', category: 'extras' },
  { name: 'Salsa de soja', keywords: 'salsa de soja,soja,salsa soja', calories: 10, serving_size: 'cucharada', category: 'extras' },
];

