import type { HubtifyApi } from './types';

/**
 * The ONE table that defines `window.api`. preload.ts (Electron) and
 * src/mobile/install-api.ts (Android, Fase 2) both build the API from it via
 * shared/build-api.ts, so adding a method = one entry here + its type in
 * HubtifyApi. `satisfies` makes a missing or extra key a type error.
 */
export type ChannelKind = 'invoke' | 'send' | 'on';

export interface ChannelSpec {
  channel: string;
  kind: ChannelKind;
  /** Absent = available on every platform. */
  platforms?: 'desktop';
  /** kind 'on' only: reshape the payload before the renderer callback. */
  unwrap?: (payload: unknown) => unknown;
}

export const API_CHANNELS = {
  getRpgStats: { channel: 'rpg:getStats', kind: 'invoke' },
  processRpgEvent: { channel: 'rpg:processEvent', kind: 'invoke' },
  rpgSetInnMode: { channel: 'rpg:setInnMode', kind: 'invoke' },
  rpgGetAchievements: { channel: 'rpg:getAchievements', kind: 'invoke' },
  rpgBackfillAchievements: { channel: 'rpg:backfillAchievements', kind: 'invoke' },
  rpgGetDaySummary: { channel: 'rpg:getDaySummary', kind: 'invoke' },
  rpgSealDay: { channel: 'rpg:sealDay', kind: 'invoke' },
  rpgGetSeals: { channel: 'rpg:getSeals', kind: 'invoke' },
  rpgGetObolosBalance: { channel: 'rpg:getObolosBalance', kind: 'invoke' },
  rpgGetRewards: { channel: 'rpg:getRewards', kind: 'invoke' },
  rpgSaveReward: { channel: 'rpg:saveReward', kind: 'invoke' },
  rpgDeleteReward: { channel: 'rpg:deleteReward', kind: 'invoke' },
  rpgRedeemReward: { channel: 'rpg:redeemReward', kind: 'invoke' },
  rpgGetShopCatalog: { channel: 'rpg:getShopCatalog', kind: 'invoke' },
  rpgPurchaseShopItem: { channel: 'rpg:purchaseShopItem', kind: 'invoke' },
  rpgEquipShopItem: { channel: 'rpg:equipShopItem', kind: 'invoke' },
  rpgGetMasteries: { channel: 'rpg:getMasteries', kind: 'invoke' },
  getRpgHistory: { channel: 'rpg:getHistory', kind: 'invoke' },
  rpgGetDashboardStats: { channel: 'rpg:getDashboardStats', kind: 'invoke' },
  windowMinimize: { channel: 'window:minimize', kind: 'send' },
  windowMaximize: { channel: 'window:maximize', kind: 'send' },
  windowClose: { channel: 'window:close', kind: 'send' },
  // Quests
  questsGetTasks: { channel: 'quests:getTasks', kind: 'invoke' },
  questsUpsertTask: { channel: 'quests:upsertTask', kind: 'invoke' },
  questsDeleteTasks: { channel: 'quests:deleteTasks', kind: 'invoke' },
  questsSetTaskStatus: { channel: 'quests:setTaskStatus', kind: 'invoke' },
  questsSyncTaskOrders: { channel: 'quests:syncTaskOrders', kind: 'invoke' },
  questsPostponeTasks: { channel: 'quests:postponeTasks', kind: 'invoke' },
  questsGetSubtasks: { channel: 'quests:getSubtasks', kind: 'invoke' },
  questsAddSubtask: { channel: 'quests:addSubtask', kind: 'invoke' },
  questsUpdateSubtask: { channel: 'quests:updateSubtask', kind: 'invoke' },
  questsDeleteSubtask: { channel: 'quests:deleteSubtask', kind: 'invoke' },
  questsSetSubtaskStatus: { channel: 'quests:setSubtaskStatus', kind: 'invoke' },
  questsSyncSubtaskOrders: { channel: 'quests:syncSubtaskOrders', kind: 'invoke' },
  questsGetCategories: { channel: 'quests:getCategories', kind: 'invoke' },
  questsEnsureCategory: { channel: 'quests:ensureCategory', kind: 'invoke' },
  questsGetDrawings: { channel: 'quests:getDrawings', kind: 'invoke' },
  questsGetDrawingCount: { channel: 'quests:getDrawingCount', kind: 'invoke' },
  questsGetAllDrawingCounts: { channel: 'quests:getAllDrawingCounts', kind: 'invoke' },
  questsSaveDrawing: { channel: 'quests:saveDrawing', kind: 'invoke' },
  questsDeleteDrawing: { channel: 'quests:deleteDrawing', kind: 'invoke' },
  questsGetHabitHeatmap: { channel: 'quests:getHabitHeatmap', kind: 'invoke' },
  questsGetHabitHistory: { channel: 'quests:getHabitHistory', kind: 'invoke' },
  questsGetHabits: { channel: 'quests:getHabits', kind: 'invoke' },
  questsAddHabit: { channel: 'quests:addHabit', kind: 'invoke' },
  questsUpdateHabit: { channel: 'quests:updateHabit', kind: 'invoke' },
  questsDeleteHabit: { channel: 'quests:deleteHabit', kind: 'invoke' },
  questsCheckHabit: { channel: 'quests:checkHabit', kind: 'invoke' },
  questsSkipHabit: { channel: 'quests:skipHabit', kind: 'invoke' },
  questsCheckHabitForDate: { channel: 'quests:checkHabitForDate', kind: 'invoke' },
  questsGetProjects: { channel: 'quests:getProjects', kind: 'invoke' },
  questsUpsertProject: { channel: 'quests:upsertProject', kind: 'invoke' },
  questsDeleteProject: { channel: 'quests:deleteProject', kind: 'invoke' },
  questsSyncProjectOrders: { channel: 'quests:syncProjectOrders', kind: 'invoke' },
  questsCountCompletedToday: { channel: 'quests:countCompletedToday', kind: 'invoke' },
  questsGetPendingCount: { channel: 'quests:getPendingCount', kind: 'invoke' },
  questsGetCompletedTodayCount: { channel: 'quests:getCompletedTodayCount', kind: 'invoke' },
  questsGetOverdueCount: { channel: 'quests:getOverdueCount', kind: 'invoke' },
  questsGetEntryDefaults: { channel: 'quests:getEntryDefaults', kind: 'invoke' },
  // Nutrition
  nutritionGetProfile: { channel: 'nutrition:getProfile', kind: 'invoke' },
  nutritionSaveProfile: { channel: 'nutrition:saveProfile', kind: 'invoke' },
  nutritionLogFood: { channel: 'nutrition:logFood', kind: 'invoke' },
  nutritionGetFoodByDate: { channel: 'nutrition:getFoodByDate', kind: 'invoke' },
  nutritionCopyDay: { channel: 'nutrition:copyDay', kind: 'invoke' },
  nutritionSearchHistory: { channel: 'nutrition:searchHistory', kind: 'invoke' },
  nutritionGetEventDays: { channel: 'nutrition:getEventDays', kind: 'invoke' },
  nutritionGetCachedEstimate: { channel: 'nutrition:getCachedEstimate', kind: 'invoke' },
  nutritionCacheEstimate: { channel: 'nutrition:cacheEstimate', kind: 'invoke' },
  nutritionGetUserCorrections: { channel: 'nutrition:getUserCorrections', kind: 'invoke' },
  nutritionDeleteFood: { channel: 'nutrition:deleteFood', kind: 'invoke' },
  nutritionDeleteByDate: { channel: 'nutrition:deleteByDate', kind: 'invoke' },
  nutritionRepeatDay: { channel: 'nutrition:repeatDay', kind: 'invoke' },
  nutritionGetRecentLoggedDays: { channel: 'nutrition:getRecentLoggedDays', kind: 'invoke' },
  nutritionUpdateFood: { channel: 'nutrition:updateFood', kind: 'invoke' },
  nutritionGetFrequentFoods: { channel: 'nutrition:getFrequentFoods', kind: 'invoke' },
  nutritionCreateFrequentFood: { channel: 'nutrition:createFrequentFood', kind: 'invoke' },
  nutritionDeleteFrequentFood: { channel: 'nutrition:deleteFrequentFood', kind: 'invoke' },
  nutritionIncrementFrequentUsage: { channel: 'nutrition:incrementFrequentUsage', kind: 'invoke' },
  nutritionGetDailyMetrics: { channel: 'nutrition:getDailyMetrics', kind: 'invoke' },
  nutritionSaveDailyMetrics: { channel: 'nutrition:saveDailyMetrics', kind: 'invoke' },
  nutritionGetWeeklyMetrics: { channel: 'nutrition:getWeeklyMetrics', kind: 'invoke' },
  nutritionSaveWeeklyMetrics: { channel: 'nutrition:saveWeeklyMetrics', kind: 'invoke' },
  nutritionGetSummary: { channel: 'nutrition:getSummary', kind: 'invoke' },
  nutritionGetSummaryRange: { channel: 'nutrition:getSummaryRange', kind: 'invoke' },
  nutritionGetMacroTargets: { channel: 'nutrition:getMacroTargets', kind: 'invoke' },
  nutritionGetWeights: { channel: 'nutrition:getWeights', kind: 'invoke' },
  nutritionGetAdaptiveTdee: { channel: 'nutrition:getAdaptiveTdee', kind: 'invoke' },
  nutritionGetStreak: { channel: 'nutrition:getStreak', kind: 'invoke' },
  nutritionGetWeekCalories: { channel: 'nutrition:getWeekCalories', kind: 'invoke' },
  nutritionGetTodayCalories: { channel: 'nutrition:getTodayCalories', kind: 'invoke' },
  nutritionGetTodayMealsCount: { channel: 'nutrition:getTodayMealsCount', kind: 'invoke' },
  nutritionGetTodayTarget: { channel: 'nutrition:getTodayTarget', kind: 'invoke' },
  nutritionCloseDay: { channel: 'nutrition:closeDay', kind: 'invoke' },
  nutritionIsDayClosed: { channel: 'nutrition:isDayClosed', kind: 'invoke' },
  nutritionReopenDay: { channel: 'nutrition:reopenDay', kind: 'invoke' },
  nutritionShouldAskWeight: { channel: 'nutrition:shouldAskWeight', kind: 'invoke' },
  nutritionGetFavoriteFoods: { channel: 'nutrition:getFavoriteFoods', kind: 'invoke' },
  nutritionAddFavoriteFood: { channel: 'nutrition:addFavoriteFood', kind: 'invoke' },
  nutritionRemoveFavoriteFood: { channel: 'nutrition:removeFavoriteFood', kind: 'invoke' },
  nutritionGetPendingDays: { channel: 'nutrition:getPendingDays', kind: 'invoke' },
  nutritionGetMealSchedule: { channel: 'nutrition:getMealSchedule', kind: 'invoke' },
  nutritionGetPendingWeeks: { channel: 'nutrition:getPendingWeeks', kind: 'invoke' },
  nutritionGetWeekReport: { channel: 'nutrition:getWeekReport', kind: 'invoke' },
  nutritionCloseWeek: { channel: 'nutrition:closeWeek', kind: 'invoke' },
  nutritionGetClosedWeeks: { channel: 'nutrition:getClosedWeeks', kind: 'invoke' },
  // Character
  characterSave: { channel: 'character:save', kind: 'invoke' },
  characterLoad: { channel: 'character:load', kind: 'invoke' },
  characterGetName: { channel: 'character:getName', kind: 'invoke' },
  characterSetName: { channel: 'character:setName', kind: 'invoke' },
  characterGetUsername: { channel: 'character:getUsername', kind: 'invoke' },
  characterSetUsername: { channel: 'character:setUsername', kind: 'invoke' },
  // Sync
  syncRestoreStats: { channel: 'sync:restoreStats', kind: 'invoke' },
  syncGetAllQuestData: { channel: 'sync:getAllQuestData', kind: 'invoke' },
  syncMergeQuestData: { channel: 'sync:mergeQuestData', kind: 'invoke' },
  syncGetAllNutritionData: { channel: 'sync:getAllNutritionData', kind: 'invoke' },
  syncMergeNutritionData: { channel: 'sync:mergeNutritionData', kind: 'invoke' },
  syncGetAllFinanceData: { channel: 'sync:getAllFinanceData', kind: 'invoke' },
  syncMergeFinanceData: { channel: 'sync:mergeFinanceData', kind: 'invoke' },
  syncClearUserData: { channel: 'sync:clearUserData', kind: 'invoke' },
  syncSetCurrentUser: { channel: 'sync:setCurrentUser', kind: 'invoke' },
  syncGetCurrentUser: { channel: 'sync:getCurrentUser', kind: 'invoke' },
  syncGetAllNotificationData: { channel: 'sync:getAllNotificationData', kind: 'invoke' },
  syncMergeNotificationData: { channel: 'sync:mergeNotificationData', kind: 'invoke' },
  syncGetAllCauldronData: { channel: 'sync:getAllCauldronData', kind: 'invoke' },
  syncMergeCauldronData: { channel: 'sync:mergeCauldronData', kind: 'invoke' },
  // Backup
  backupExport: { channel: 'backup:export', kind: 'invoke', platforms: 'desktop' },
  backupPickImportFile: { channel: 'backup:pickImportFile', kind: 'invoke', platforms: 'desktop' },
  backupImport: { channel: 'backup:import', kind: 'invoke', platforms: 'desktop' },
  // Notifications
  notificationsSend: { channel: 'notifications:send', kind: 'invoke' },
  notificationsGetAll: { channel: 'notifications:getAll', kind: 'invoke' },
  notificationsDismiss: { channel: 'notifications:dismiss', kind: 'invoke' },
  notificationsSnooze: { channel: 'notifications:snooze', kind: 'invoke' },
  notificationsRunCheck: { channel: 'notifications:runCheck', kind: 'invoke' },
  notificationsGetCount: { channel: 'notifications:getCount', kind: 'invoke' },
  notificationsSetSystemEnabled: { channel: 'notifications:setSystemEnabled', kind: 'invoke' },
  notificationsSetLocale: { channel: 'notifications:setLocale', kind: 'invoke' },
  notificationsSetModuleEnabled: { channel: 'notifications:setModuleEnabled', kind: 'invoke' },
  notificationsSetHabitReminder: { channel: 'notifications:setHabitReminder', kind: 'invoke' },
  notificationsExactAlarmState: { channel: 'notifications:exactAlarmState', kind: 'invoke' },
  notificationsRequestExactAlarms: { channel: 'notifications:requestExactAlarms', kind: 'invoke' },
  onRpgAchievementUnlocked: { channel: 'rpg:achievementUnlocked', kind: 'on', unwrap: (p: unknown) => (p as { id?: string } | undefined)?.id },
  onRpgAchievementsBackfilled: { channel: 'rpg:achievementsBackfilled', kind: 'on', unwrap: (p: unknown) => (p as { ids?: string[] } | undefined)?.ids ?? [] },
  onRpgDaySealed: { channel: 'rpg:daySealed', kind: 'on' },
  onRpgPardonUsed: { channel: 'rpg:pardonUsed', kind: 'on' },
  onNotificationsUpdated: { channel: 'notifications:updated', kind: 'on' },
  // Cauldron
  cauldronGetPresets: { channel: 'cauldron:getPresets', kind: 'invoke' },
  cauldronGetLastUsedPreset: { channel: 'cauldron:getLastUsedPreset', kind: 'invoke' },
  cauldronUpsertPreset: { channel: 'cauldron:upsertPreset', kind: 'invoke' },
  cauldronDeletePreset: { channel: 'cauldron:deletePreset', kind: 'invoke' },
  cauldronStart: { channel: 'cauldron:start', kind: 'invoke' },
  cauldronPause: { channel: 'cauldron:pause', kind: 'invoke' },
  cauldronResume: { channel: 'cauldron:resume', kind: 'invoke' },
  cauldronSkip: { channel: 'cauldron:skip', kind: 'invoke' },
  cauldronConfirmNext: { channel: 'cauldron:confirmNext', kind: 'invoke' },
  cauldronExtend: { channel: 'cauldron:extend', kind: 'invoke' },
  cauldronStop: { channel: 'cauldron:stop', kind: 'invoke' },
  cauldronGetState: { channel: 'cauldron:getState', kind: 'invoke' },
  cauldronGetStats: { channel: 'cauldron:getStats', kind: 'invoke' },
  cauldronGetSessions: { channel: 'cauldron:getSessions', kind: 'invoke' },
  cauldronGetWeeklyFocusTime: { channel: 'cauldron:getWeeklyFocusTime', kind: 'invoke' },
  cauldronGetInterruptedSession: { channel: 'cauldron:getInterruptedSession', kind: 'invoke' },
  cauldronResumeInterruptedSession: { channel: 'cauldron:resumeInterruptedSession', kind: 'invoke' },
  cauldronDiscardInterruptedSession: { channel: 'cauldron:discardInterruptedSession', kind: 'invoke' },
  cauldronCancelAutoStart: { channel: 'cauldron:cancelAutoStart', kind: 'invoke' },
  cauldronSetSessionTask: { channel: 'cauldron:setSessionTask', kind: 'invoke' },
  cauldronLogPastSession: { channel: 'cauldron:logPastSession', kind: 'invoke' },
  cauldronGetWeekByProject: { channel: 'cauldron:getWeekByProject', kind: 'invoke' },
  cauldronSetLabels: { channel: 'cauldron:setLabels', kind: 'invoke' },
  onCauldronTick: { channel: 'cauldron:tick', kind: 'on' },
  onCauldronSessionEnd: { channel: 'cauldron:sessionEnd', kind: 'on' },
  cauldronOpenWindow: { channel: 'cauldron:openWindow', kind: 'invoke', platforms: 'desktop' },
  cauldronCloseWindow: { channel: 'cauldron:closeWindow', kind: 'invoke', platforms: 'desktop' },
  onCauldronWindowOpened: { channel: 'cauldron:windowOpened', kind: 'on' },
  onCauldronWindowClosed: { channel: 'cauldron:windowClosed', kind: 'on' },
  // Dollar
  dollarGetRates: { channel: 'dollar:getRates', kind: 'invoke' },
  dollarGetFxHouse: { channel: 'dollar:getFxHouse', kind: 'invoke' },
  dollarSetFxHouse: { channel: 'dollar:setFxHouse', kind: 'invoke' },
  dollarGetCurrentRate: { channel: 'dollar:getCurrentRate', kind: 'invoke' },
  financeBackfillFxRates: { channel: 'finance:backfillFxRates', kind: 'invoke' },
  financeGetValuedView: { channel: 'finance:getValuedView', kind: 'invoke' },
  financeGetInflationSeries: { channel: 'finance:getInflationSeries', kind: 'invoke' },
  financeGetUpcoming: { channel: 'finance:getUpcoming', kind: 'invoke' },
  financeGetAccounts: { channel: 'finance:getAccounts', kind: 'invoke' },
  financeGetAccountsOverview: { channel: 'finance:getAccountsOverview', kind: 'invoke' },
  financeSaveAccount: { channel: 'finance:saveAccount', kind: 'invoke' },
  financeDeleteAccount: { channel: 'finance:deleteAccount', kind: 'invoke' },
  financeTransferBetweenAccounts: { channel: 'finance:transferBetweenAccounts', kind: 'invoke' },
  dollarGetVisibleTypes: { channel: 'dollar:getVisibleTypes', kind: 'invoke' },
  dollarSetVisibleTypes: { channel: 'dollar:setVisibleTypes', kind: 'invoke' },
  // Crypto
  cryptoGetRates: { channel: 'crypto:getRates', kind: 'invoke' },
  cryptoGetVisibleTypes: { channel: 'crypto:getVisibleTypes', kind: 'invoke' },
  cryptoSetVisibleTypes: { channel: 'crypto:setVisibleTypes', kind: 'invoke' },
  // Finance - Transactions
  financeGetTransactions: { channel: 'finance:getTransactions', kind: 'invoke' },
  financeAddTransaction: { channel: 'finance:addTransaction', kind: 'invoke' },
  financeUpdateTransaction: { channel: 'finance:updateTransaction', kind: 'invoke' },
  financeDeleteTransaction: { channel: 'finance:deleteTransaction', kind: 'invoke' },
  // Finance - Installments
  financeGetInstallmentGroups: { channel: 'finance:getInstallmentGroups', kind: 'invoke' },
  financeGetInstallmentsForMonth: { channel: 'finance:getInstallmentsForMonth', kind: 'invoke' },
  financeGetInstallmentProjection: { channel: 'finance:getInstallmentProjection', kind: 'invoke' },
  financeCreateInstallmentGroup: { channel: 'finance:createInstallmentGroup', kind: 'invoke' },
  financeDeleteInstallmentGroup: { channel: 'finance:deleteInstallmentGroup', kind: 'invoke' },
  financeUpdateInstallmentAmount: { channel: 'finance:updateInstallmentAmount', kind: 'invoke' },
  // Finance - Loans
  financeGetLoans: { channel: 'finance:getLoans', kind: 'invoke' },
  financeGetLoansByPerson: { channel: 'finance:getLoansByPerson', kind: 'invoke' },
  financeAddLoan: { channel: 'finance:addLoan', kind: 'invoke' },
  financeSettleLoan: { channel: 'finance:settleLoan', kind: 'invoke' },
  financeAddLoanPayment: { channel: 'finance:addLoanPayment', kind: 'invoke' },
  financeGetLoanPayments: { channel: 'finance:getLoanPayments', kind: 'invoke' },
  financeDeleteLoanPayment: { channel: 'finance:deleteLoanPayment', kind: 'invoke' },
  financeCreateThirdPartyPurchase: { channel: 'finance:createThirdPartyPurchase', kind: 'invoke' },
  financeGetActiveLoanSummary: { channel: 'finance:getActiveLoanSummary', kind: 'invoke' },
  // Finance - Recurring
  financeGetRecurring: { channel: 'finance:getRecurring', kind: 'invoke' },
  financeAddRecurring: { channel: 'finance:addRecurring', kind: 'invoke' },
  financeUpdateRecurringAmount: { channel: 'finance:updateRecurringAmount', kind: 'invoke' },
  financeUpdateRecurring: { channel: 'finance:updateRecurring', kind: 'invoke' },
  financeToggleRecurring: { channel: 'finance:toggleRecurring', kind: 'invoke' },
  financeDeleteRecurring: { channel: 'finance:deleteRecurring', kind: 'invoke' },
  financeGenerateRecurringForMonth: { channel: 'finance:generateRecurringForMonth', kind: 'invoke' },
  financeGetRecurringAmountHistory: { channel: 'finance:getRecurringAmountHistory', kind: 'invoke' },
  // Finance - Import
  financeImportPickPdf: { channel: 'finance:importPickPdf', kind: 'invoke' },
  financeImportParsePdfText: { channel: 'finance:importParsePdfText', kind: 'invoke' },
  financeImportConfirm: { channel: 'finance:importConfirm', kind: 'invoke' },
  financeUndoImportBatch: { channel: 'finance:undoImportBatch', kind: 'invoke' },
  financeGetImportBatches: { channel: 'finance:getImportBatches', kind: 'invoke' },
  financeGetCategoryMappings: { channel: 'finance:getCategoryMappings', kind: 'invoke' },
  financeGetBudgets: { channel: 'finance:getBudgets', kind: 'invoke' },
  financeSetBudget: { channel: 'finance:setBudget', kind: 'invoke' },
  financeGetBudgetStatus: { channel: 'finance:getBudgetStatus', kind: 'invoke' },
  financeUpdateCategoryMapping: { channel: 'finance:updateCategoryMapping', kind: 'invoke' },
  financeSaveStatementPaper: { channel: 'finance:saveStatementPaper', kind: 'invoke' },
  financeImportSelectAndParseTable: { channel: 'finance:importSelectAndParseTable', kind: 'invoke' },
  financeImportApplyTableMapping: { channel: 'finance:importApplyTableMapping', kind: 'invoke' },
  financeImportConfirmTable: { channel: 'finance:importConfirmTable', kind: 'invoke' },
  financeGetEntryDefaults: { channel: 'finance:getEntryDefaults', kind: 'invoke' },
  // Finance - Dashboard
  financeGetMonthlyBalance: { channel: 'finance:getMonthlyBalance', kind: 'invoke' },
  financeGetCategoryBreakdown: { channel: 'finance:getCategoryBreakdown', kind: 'invoke' },
  financeGetBalanceForRange: { channel: 'finance:getBalanceForRange', kind: 'invoke' },
  financeGetCategoryBreakdownForRange: { channel: 'finance:getCategoryBreakdownForRange', kind: 'invoke' },
  financeGetProjection: { channel: 'finance:getProjection', kind: 'invoke' },
  // Finance - Export
  financeExportCsv: { channel: 'finance:exportCsv', kind: 'invoke' },
  // Finance - Dashboard (new)
  financeGetMonthlyExpenses: { channel: 'finance:getMonthlyExpenses', kind: 'invoke' },
  financeGetCategoryAverages: { channel: 'finance:getCategoryAverages', kind: 'invoke' },
  financeGetPreviousMonthSummary: { channel: 'finance:getPreviousMonthSummary', kind: 'invoke' },
  // Finance - Backward compat
  financeGetMonthlyTotal: { channel: 'finance:getMonthlyTotal', kind: 'invoke' },
  financeGetActiveLoansCount: { channel: 'finance:getActiveLoansCount', kind: 'invoke' },
  financeGetTodayTransactionsCount: { channel: 'finance:getTodayTransactionsCount', kind: 'invoke' },
  financeGetCategories: { channel: 'finance:getCategories', kind: 'invoke' },
  financeAddCategory: { channel: 'finance:addCategory', kind: 'invoke' },
  financeDeleteCategory: { channel: 'finance:deleteCategory', kind: 'invoke' },
  // Finance - Credit Cards
  financeGetCreditCards: { channel: 'finance:getCreditCards', kind: 'invoke' },
  financeAddCreditCard: { channel: 'finance:addCreditCard', kind: 'invoke' },
  financeUpdateCreditCard: { channel: 'finance:updateCreditCard', kind: 'invoke' },
  financeDeleteCreditCard: { channel: 'finance:deleteCreditCard', kind: 'invoke' },
  financeGetCreditCardStatements: { channel: 'finance:getCreditCardStatements', kind: 'invoke' },
  financeGetStatementDetail: { channel: 'finance:getStatementDetail', kind: 'invoke' },
  financeGenerateStatement: { channel: 'finance:generateStatement', kind: 'invoke' },
  financePayStatement: { channel: 'finance:payStatement', kind: 'invoke' },
  financeGetExpenseBreakdown: { channel: 'finance:getExpenseBreakdown', kind: 'invoke' },
  financeGetExpenseBreakdownForRange: { channel: 'finance:getExpenseBreakdownForRange', kind: 'invoke' },
  // Feedback
  feedbackSend: { channel: 'feedback:send', kind: 'invoke' },
  // Syl (read-projection snapshot)
  sylBuildSnapshot: { channel: 'syl:buildSnapshot', kind: 'invoke' },
  // Instalación duplicada de Squirrel (solo Windows empaquetado)
  getInstallWarning: { channel: 'app:getInstallWarning', kind: 'invoke', platforms: 'desktop' },
  // Updater
  updaterCheck: { channel: 'updater:check', kind: 'invoke', platforms: 'desktop' },
  updaterDownload: { channel: 'updater:download', kind: 'invoke', platforms: 'desktop' },
  updaterRestart: { channel: 'updater:restart', kind: 'invoke', platforms: 'desktop' },
  onUpdateAvailable: { channel: 'updater:update-available', kind: 'on' },
  onUpdateDownloaded: { channel: 'updater:update-downloaded', kind: 'on', unwrap: () => undefined },
  onDownloadProgress: { channel: 'updater:download-progress', kind: 'on' },
  onUpdateError: { channel: 'updater:error', kind: 'on' },
} as const satisfies Record<keyof HubtifyApi, ChannelSpec>;

export type ApiKey = keyof typeof API_CHANNELS;
